default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= Figaro.env.database_username %>
  password: <%= Figaro.env.database_password %>
  timeout: 5000
  #socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: <%= Figaro.env.database_name %>


